### ISSUE TITLE
安装的问题

### ISSUE THREAD

**Issue by ghgithub** [yanxiaojun617/com.kit.cordova.amapnavigation#2]
![image](https://user-images.githubusercontent.com/3312606/40172893-9d920eb2-5a02-11e8-8f02-16bf6ec9ac9e.png)

**Comment by xiaosan666** [comment]
cordova plugin add https://github.com/yanxiaojun617/com.kit.cordova.amapnavigation.git --save

**Comment by ghgithub** [comment]
直接用高德地图的定位SDK的源码OK解决
